apiVersion: v2
name: auth-svc
description: Observatory Auth Service — OIDC-based authentication
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - observatory
  - auth
  - oidc
  - jwt
maintainers:
  - name: luciocarvalhojr
